ci: create a new subnetwork for each new GKE cluster
We sometimes hit this issue in the CI for runs involving GKE clusters:

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=This operation will exceed max secondary ranges per subnetwork (30) for subnet "default", consider reusing existing secondary ranges or use a different subnetwork.
```

As per the documentation, we can have the `gcloud` CLI create a new
subnet when creating a new GKE cluster with `--create-subnetwork`.
When passed `""`, it creates a new subnet with a default name and size.
The goal here is to make sure that clusters don't conflict with each
others in the default subnet when there are too many secondary ranges
used at the same time.

The option also requires use of `--enable-ip-alias`, which should have
no impact for us.

Doc: https://cloud.google.com/sdk/gcloud/reference/container/clusters/create

Signed-off-by: Nicolas Busseneau <nicolas@isovalent.com>